name: CI

on:
  push:
    branches: [ "release/*" ]
  pull_request:
    branches: [ "release/*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:          
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: yyych0602/cicd:v1.0

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Send a Message 
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "Name: ${{ secrets.SLACK_NAME }} \n Matriculation numbers: ${{ secrets.SLACK_MATRIC }} \n Email: ${{ secrets.SLACK_EMAIL }} \n Repo: ${{ github.repositoryUrl }} \n Image Name: ${{ secrets.IMAGENAME }}  \n Image url: ${{ secrets.IMAGE }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
